# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/is11lg/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries

PRODUCT_COPY_FILES += \
  vendor/lge/is11lg/proprietary/etc/nvcamera.conf:system/etc/nvcamera.conf \
  vendor/lge/is11lg/proprietary/etc/ipc_channels.config:system/etc/ipc_channels.config \
  vendor/lge/is11lg/proprietary/bin/BCM43291A0_003.001.013.0111.0130.hcd:system/bin/BCM43291A0_003.001.013.0111.0130.hcd \
  vendor/lge/is11lg/proprietary/etc/firmware/nvmm_aacdec.axf:system/etc/firmware/nvmm_aacdec.axf \
  vendor/lge/is11lg/proprietary/etc/firmware/nvmm_adtsdec.axf:system/etc/firmware/nvmm_adtsdec.axf \
  vendor/lge/is11lg/proprietary/etc/firmware/nvmm_h264dec.axf:system/etc/firmware/nvmm_h264dec.axf \
  vendor/lge/is11lg/proprietary/etc/firmware/nvmm_jpegdec.axf:system/etc/firmware/nvmm_jpegdec.axf \
  vendor/lge/is11lg/proprietary/etc/firmware/nvmm_jpegenc.axf:system/etc/firmware/nvmm_jpegenc.axf \
  vendor/lge/is11lg/proprietary/etc/firmware/nvmm_manager.axf:system/etc/firmware/nvmm_manager.axf \
  vendor/lge/is11lg/proprietary/etc/firmware/nvmm_mp3dec.axf:system/etc/firmware/nvmm_mp3dec.axf \
  vendor/lge/is11lg/proprietary/etc/firmware/nvmm_mpeg4dec.axf:system/etc/firmware/nvmm_mpeg4dec.axf \
  vendor/lge/is11lg/proprietary/etc/firmware/nvmm_reference.axf:system/etc/firmware/nvmm_reference.axf \
  vendor/lge/is11lg/proprietary/etc/firmware/nvmm_service.axf:system/etc/firmware/nvmm_service.axf \
  vendor/lge/is11lg/proprietary/etc/firmware/nvmm_vc1dec.axf:system/etc/firmware/nvmm_vc1dec.axf \
  vendor/lge/is11lg/proprietary/etc/firmware/nvmm_vc1dec_2x.axf:system/etc/firmware/nvmm_vc1dec_2x.axf \
  vendor/lge/is11lg/proprietary/etc/firmware/nvmm_wavdec.axf:system/etc/firmware/nvmm_wavdec.axf \
  vendor/lge/is11lg/proprietary/etc/firmware/nvmm_wmadec.axf:system/etc/firmware/nvmm_wmadec.axf \
  vendor/lge/is11lg/proprietary/etc/firmware/nvmm_wmaprodec.axf:system/etc/firmware/nvmm_wmaprodec.axf \
  vendor/lge/is11lg/proprietary/etc/firmware/nvrm_avp.bin:system/etc/firmware/nvrm_avp.bin \
  vendor/lge/is11lg/proprietary/etc/wifi/fw_bcm4329.bin:system/etc/wifi/fw_bcm4329.bin \
  vendor/lge/is11lg/proprietary/etc/wifi/fw_bcm4329_ap.bin:system/etc/wifi/fw_bcm4329_ap.bin \
  vendor/lge/is11lg/proprietary/etc/wifi/fw_bcm4329_apsta.bin:system/etc/wifi/fw_bcm4329_apsta.bin \
  vendor/lge/is11lg/proprietary/etc/wifi/fw_bcm4329_mfg.bin:system/etc/wifi/fw_bcm4329_mfg.bin \
  vendor/lge/is11lg/proprietary/etc/wifi/fw_bcm4329_p2p.bin:system/etc/wifi/fw_bcm4329_p2p.bin \
  vendor/lge/is11lg/proprietary/etc/wifi/nvram.txt:system/etc/wifi/nvram.txt \
  vendor/lge/is11lg/proprietary/etc/cert/lge.cer:system/etc/cert/lge.cer \
  vendor/lge/is11lg/proprietary/lib/liblgdrm.so:system/lib/liblgdrm.so \
  vendor/lge/is11lg/proprietary/lib/libril.so:system/lib/libril.so \
  vendor/lge/is11lg/proprietary/lib/libnvrm_graphics.so:system/lib/libnvrm_graphics.so \
  vendor/lge/is11lg/proprietary/lib/libnvsm.so:system/lib/libnvsm.so \
  vendor/lge/is11lg/proprietary/lib/libnvsystemuiext_jni.so:system/lib/libnvsystemuiext_jni.so \
  vendor/lge/is11lg/proprietary/lib/libnvos.so:system/lib/libnvos.so \
  vendor/lge/is11lg/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
  vendor/lge/is11lg/proprietary/lib/libnvodm_query.so:system/lib/libnvodm_query.so \
  vendor/lge/is11lg/proprietary/lib/libnvmm_utils.so:system/lib/libnvmm_utils.so \
  vendor/lge/is11lg/proprietary/lib/libnvmmlite_video.so:system/lib/libnvmmlite_video.so \
  vendor/lge/is11lg/proprietary/lib/libnvwinsys.so:system/lib/libnvwinsys.so \
  vendor/lge/is11lg/proprietary/lib/libnvmm_video.so:system/lib/libnvmm_video.so \
  vendor/lge/is11lg/proprietary/lib/libnvmm_camera.so:system/lib/libnvmm_camera.so \
  vendor/lge/is11lg/proprietary/lib/libnvaviparserhal.so:system/lib/libnvaviparserhal.so \
  vendor/lge/is11lg/proprietary/lib/libnvmm_service.so:system/lib/libnvmm_service.so \
  vendor/lge/is11lg/proprietary/lib/liblgdmbomxcore.so:system/lib/liblgdmbomxcore.so \
  vendor/lge/is11lg/proprietary/lib/libdivxdrm.so:system/lib/libdivxdrm.so \
  vendor/lge/is11lg/proprietary/lib/libnvcontrol_jni.so:system/lib/libnvcontrol_jni.so \
  vendor/lge/is11lg/proprietary/lib/libnvddk_2d_v2.so:system/lib/libnvddk_2d_v2.so \
  vendor/lge/is11lg/proprietary/lib/libnvavp.so:system/lib/libnvavp.so \
  vendor/lge/is11lg/proprietary/lib/libnvomxadaptor.so:system/lib/libnvomxadaptor.so \
  vendor/lge/is11lg/proprietary/lib/libnvrm.so:system/lib/libnvrm.so \
  vendor/lge/is11lg/proprietary/lib/hw/hwcomposer.tegra.so:system/lib/hw/hwcomposer.tegra.so \
  vendor/lge/is11lg/proprietary/lib/hw/audio.primary.tegra.so:system/lib/hw/audio.primary.tegra.so \
  vendor/lge/is11lg/proprietary/lib/hw/audio_policy.tegra.so:system/lib/hw/audio_policy.tegra.so \
  vendor/lge/is11lg/proprietary/lib/hw/gps.tegra.so:system/lib/hw/gps.tegra.so \
  vendor/lge/is11lg/proprietary/lib/hw/sensors.tegra.so:system/lib/hw/sensors.tegra.so \
  vendor/lge/is11lg/proprietary/lib/hw/camera.tegra.so:system/lib/hw/camera.tegra.so \
  vendor/lge/is11lg/proprietary/lib/hw/gralloc.tegra.so:system/lib/hw/gralloc.tegra.so \
  vendor/lge/is11lg/proprietary/lib/libini.so:system/lib/libini.so \
  vendor/lge/is11lg/proprietary/lib/libnvtestio.so:system/lib/libnvtestio.so \
  vendor/lge/is11lg/proprietary/lib/libnvmm.so:system/lib/libnvmm.so \
  vendor/lge/is11lg/proprietary/lib/libnvmm_image.so:system/lib/libnvmm_image.so \
  vendor/lge/is11lg/proprietary/lib/libmpl.so:system/lib/libmpl.so \
  vendor/lge/is11lg/proprietary/lib/libnvmm_contentpipe.so:system/lib/libnvmm_contentpipe.so \
  vendor/lge/is11lg/proprietary/lib/libmllite.so:system/lib/libmllite.so \
  vendor/lge/is11lg/proprietary/lib/libnvcpud.so:system/lib/libnvcpud.so \
  vendor/lge/is11lg/proprietary/lib/libcgdrv.so:system/lib/libcgdrv.so \
  vendor/lge/is11lg/proprietary/lib/libsktdrm_sf_wrap.so:system/lib/libsktdrm_sf_wrap.so \
  vendor/lge/is11lg/proprietary/lib/liblgemmevrc.so:system/lib/liblgemmevrc.so \
  vendor/lge/is11lg/proprietary/lib/libmlplatform.so:system/lib/libmlplatform.so \
  vendor/lge/is11lg/proprietary/lib/libnvtvmr.so:system/lib/libnvtvmr.so \
  vendor/lge/is11lg/proprietary/lib/libsktdrmdevice.so:system/lib/libsktdrmdevice.so \
  vendor/lge/is11lg/proprietary/lib/liblge_divxdrm.so:system/lib/liblge_divxdrm.so \
  vendor/lge/is11lg/proprietary/lib/libaudioservice.so:system/lib/libaudioservice.so \
  vendor/lge/is11lg/proprietary/lib/libnvddk_2d.so:system/lib/libnvddk_2d.so \
  vendor/lge/is11lg/proprietary/lib/libsktdrm_sf.so:system/lib/libsktdrm_sf.so \
  vendor/lge/is11lg/proprietary/lib/lge-ril.so:system/lib/lge-ril.so \
  vendor/lge/is11lg/proprietary/lib/libnvmm_parser.so:system/lib/libnvmm_parser.so \
  vendor/lge/is11lg/proprietary/lib/libnvomx.so:system/lib/libnvomx.so \
  vendor/lge/is11lg/proprietary/lib/liblgemmqcelp.so:system/lib/liblgemmqcelp.so \
  vendor/lge/is11lg/proprietary/lib/libardrv_dynamic.so:system/lib/libardrv_dynamic.so \
  vendor/lge/is11lg/proprietary/lib/libnvmmlite_utils.so:system/lib/libnvmmlite_utils.so \
  vendor/lge/is11lg/proprietary/lib/libnvmm_misc.so:system/lib/libnvmm_misc.so \
  vendor/lge/is11lg/proprietary/lib/libnvcpud_client.so:system/lib/libnvcpud_client.so \
  vendor/lge/is11lg/proprietary/lib/libstagefright_LGdmb.so:system/lib/libstagefright_LGdmb.so \
  vendor/lge/is11lg/proprietary/lib/libnvmmlite.so:system/lib/libnvmmlite.so \
  vendor/lge/is11lg/proprietary/lib/libnvasfparserhal.so:system/lib/libnvasfparserhal.so \
  vendor/lge/is11lg/proprietary/lib/libnvparser.so:system/lib/libnvparser.so \
  vendor/lge/is11lg/proprietary/lib/libnvwsi.so:system/lib/libnvwsi.so \
  vendor/lge/is11lg/proprietary/lib/libnvmm_manager.so:system/lib/libnvmm_manager.so \
  vendor/lge/is11lg/proprietary/lib/libnvomxilclient.so:system/lib/libnvomxilclient.so \
  vendor/lge/is11lg/proprietary/lib/liblvvewrapper.so:system/lib/liblvvewrapper.so \
  vendor/lge/is11lg/proprietary/lib/libasound.so:system/lib/libasound.so \
  vendor/lge/is11lg/proprietary/lib/libasound_module_rate_speexrate.so:system/lib/libasound_module_rate_speexrate.so \
  vendor/lge/is11lg/proprietary/lib/libnvmm_writer.so:system/lib/libnvmm_writer.so \
  vendor/lge/is11lg/proprietary/lib/libnvodm_misc.so:system/lib/libnvodm_misc.so \
  vendor/lge/is11lg/proprietary/lib/libnvmm_audio.so:system/lib/libnvmm_audio.so \
  vendor/lge/is11lg/proprietary/lib/libnvdispmgr_d.so:system/lib/libnvdispmgr_d.so \
  vendor/lge/is11lg/proprietary/lib/libnvhdmi3dplay_jni.so:system/lib/libnvhdmi3dplay_jni.so \
  vendor/lge/is11lg/proprietary/lib/egl/libGLESv2_tegra.so:system/lib/egl/libGLESv2_tegra.so \
  vendor/lge/is11lg/proprietary/lib/egl/libGLESv1_CM_tegra.so:system/lib/egl/libGLESv1_CM_tegra.so \
  vendor/lge/is11lg/proprietary/lib/egl/libEGL_tegra.so:system/lib/egl/libEGL_tegra.so \
  vendor/lge/is11lg/proprietary/lib/egl/libEGL_perfhud.so:system/lib/egl/libEGL_perfhud.so \
  vendor/lge/is11lg/proprietary/lib/egl/libGLESv1_CM_perfhud.so:system/lib/egl/libGLESv1_CM_perfhud.so \
  vendor/lge/is11lg/proprietary/lib/egl/libGLESv2_perfhud.so:system/lib/egl/libGLESv2_perfhud.so \
  vendor/lge/is11lg/proprietary/lib/libnvtestresults.so:system/lib/libnvtestresults.so \
  vendor/lge/is11lg/proprietary/lib/libnvmmlite_audio.so:system/lib/libnvmmlite_audio.so \
  vendor/lge/is11lg/proprietary/lib/libSKT_MusicDRM.so:system/lib/libSKT_MusicDRM.so \
  vendor/lge/is11lg/proprietary/lib/libnvodm_imager.so:system/lib/libnvodm_imager.so \
  vendor/lge/is11lg/proprietary/bin/nvcpud:system/bin/nvcpud \
  vendor/lge/is11lg/proprietary/bin/glgps:system/bin/glgps \
  vendor/lge/is11lg/proprietary/bin/rild:system/bin/rild \
  vendor/lge/is11lg/proprietary/bin/lgdrmserver:system/bin/lgdrmserver \
  vendor/lge/is11lg/proprietary/usr/share/alsa/pcm/dsnoop.conf:system/usr/share/alsa/pcm/dsnoop.conf \
  vendor/lge/is11lg/proprietary/usr/share/alsa/pcm/center_lfe.conf:system/usr/share/alsa/pcm/center_lfe.conf \
  vendor/lge/is11lg/proprietary/usr/share/alsa/pcm/modem.conf:system/usr/share/alsa/pcm/modem.conf \
  vendor/lge/is11lg/proprietary/usr/share/alsa/pcm/dpl.conf:system/usr/share/alsa/pcm/dpl.conf \
  vendor/lge/is11lg/proprietary/usr/share/alsa/pcm/default.conf:system/usr/share/alsa/pcm/default.conf \
  vendor/lge/is11lg/proprietary/usr/share/alsa/pcm/surround50.conf:system/usr/share/alsa/pcm/surround50.conf \
  vendor/lge/is11lg/proprietary/usr/share/alsa/pcm/surround51.conf:system/usr/share/alsa/pcm/surround51.conf \
  vendor/lge/is11lg/proprietary/usr/share/alsa/pcm/rear.conf:system/usr/share/alsa/pcm/rear.conf \
  vendor/lge/is11lg/proprietary/usr/share/alsa/pcm/surround71.conf:system/usr/share/alsa/pcm/surround71.conf \
  vendor/lge/is11lg/proprietary/usr/share/alsa/pcm/front.conf:system/usr/share/alsa/pcm/front.conf \
  vendor/lge/is11lg/proprietary/usr/share/alsa/pcm/surround40.conf:system/usr/share/alsa/pcm/surround40.conf \
  vendor/lge/is11lg/proprietary/usr/share/alsa/pcm/dmix.conf:system/usr/share/alsa/pcm/dmix.conf \
  vendor/lge/is11lg/proprietary/usr/share/alsa/pcm/iec958.conf:system/usr/share/alsa/pcm/iec958.conf \
  vendor/lge/is11lg/proprietary/usr/share/alsa/pcm/side.conf:system/usr/share/alsa/pcm/side.conf \
  vendor/lge/is11lg/proprietary/usr/share/alsa/pcm/surround41.conf:system/usr/share/alsa/pcm/surround41.conf \
  vendor/lge/is11lg/proprietary/usr/share/alsa/cards/aliases.conf:system/usr/share/alsa/cards/aliases.conf \
  vendor/lge/is11lg/proprietary/usr/share/alsa/alsa.conf:system/usr/share/alsa/alsa.conf
